Containerization files
beeldengeluid/dane-example-worker pull request #18
Opened 2024-03-07 15:00 UTC by greenw0lf

Linked to #3 

`.flake8` was copied from [dane-visual-feature-extraction-worker](https://github.com/beeldengeluid/dane-visual-feature-extraction-worker)

The other files pertain to Docker and are more or less the same as what the outcome of the workshop would be

2024-03-08 13:44 UTC, Veldhoen requested changes
Nice work!  I've left a few comments on specific files. 

However, it seems that something goes wrong with the installation of the dependencies. I've left a comment about this with the Dockerfile. 
If you like, we can have a look at it together next week, and perhaps ask Jaap to join if we can't manage to solve it.

2024-03-08 13:44 UTC, Veldhoen commented on Dockerfile
> +RUN chown nonroot: docker-entrypoint.sh
This solution is not working after all, so delete this line. 

What did work for me, was to change the file permissions for the entrypoint file: `chmod +x docker-entrypoint.sh`
I pushed this change to git, please check if it works properly

2024-03-08 13:44 UTC, Veldhoen commented on docker-entrypoint.sh
> +echo "The worker crashed"
This line is misleading (which is not your fault, you only copy-pasted it). 
Maybe make it "The worker has finished" or something similar.

2024-03-08 13:44 UTC, Veldhoen commented on Dockerfile
After building the image, I cannot run the worker because the dependencies cannot be found. 
Indeed, when I start the container in interactive mode (`docker run -it --rm --entrypoint bash <image-name>`) and run `poetry show`, it shows all packages in red which means they are not (properly) installed. 
When I run `poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR` (still in interactive mode), the required modules are installed. 


I looked into it a bit and am really puzzled. It seems that poetry does install all the dependencies at build time, I get no errors at least. 

Does this happen at your end too/ can you reproduce this behaviour?

2024-03-11 14:25 UTC, greenw0lf commented on Dockerfile
I will push the changes I did, some things were unclear (what to keep or remove), so let me know if anything is odd.

2024-03-11 14:26 UTC, greenw0lf commented on Dockerfile
I also kept `COPY . .` because I assumed it's copying to the wrong directory

2024-03-11 14:32 UTC, greenw0lf commented on Dockerfile
Fixed, it was Windows' newline being used (CRLF) instead of the Unix one (LF)

2024-03-12 12:39 UTC, Veldhoen approved these changes
Yes, looks good and it's working now! Or at least, the error that I get is from INSIDE the worker and not related to the containerization.

2024-03-12 13:38 UTC, Martaesplo approved these changes
The containerization worked for me as well. 
But also getting the error: AttributeError: TEST_INPUT_PATH

2024-03-12 13:40 UTC, merged