Potential fixes to run worker on test input
beeldengeluid/dane-example-worker pull request #20
Opened 2024-03-18 12:09 UTC by greenw0lf

Linked to #19 

I managed to make the worker run on test input. The error I am getting now (which I think it's fine for test input) is that the output cannot be uploaded to S3.

I removed /data and /config ignores in `.dockerignore`, as well as explicitly copied the `config.yml` file to `/root/.DANE` inside the `Dockerfile`.

I know `data` and `config.yml` should normally NOT be copied if the Docker image is published, but since this is an example worker meant as a starting template and for development/testing purposes only, this is acceptable.

I suggest making some sort of configuration for Docker such that you can have `data` and `config.yml` when testing, but in prod ignore them.

2024-03-18 12:12 UTC, greenw0lf commented
Maybe we can have different `.dockerignore` files per branch and have `prod` and `dev` branches or something similar?

2024-03-18 14:56 UTC, Veldhoen commented
We don't usually work with separate dev and prod branches, so although it may be a solution, it doesn't suit our way of working I'm afraid. 
Would it be a solution to bind mount ./config and ./data as volumes in the container? That allows you to simply add them at run time, without cluttering the image. You could then specify the instructions for doing so in the README a/o in the Wiki. 
See https://docs.docker.com/storage/bind-mounts/

2024-03-18 16:29 UTC, greenw0lf commented
Ok, I did as you suggested and it indeed worked. I will revert the Docker changes and add instructions about how to test in both the README and the wiki

2024-03-18 16:38 UTC, greenw0lf commented
@Veldhoen could you review the README explanation and let me know what you think?

2024-03-19 08:56 UTC, Veldhoen requested changes
Almost there!

2024-03-19 08:56 UTC, Veldhoen commented on Dockerfile
> +RUN mkdir /root/.DANE /mnt/dane-fs /src /src/data
Why do you inject a data dir in src? It seems more logical to me to add it at root level (just `/data`)
And then configure this in the config.yml: 
```
FILE_SYSTEM:
    BASE_MOUNT: /data
```

2024-03-19 08:56 UTC, Veldhoen commented on README.md
I think your explanation makes sense! Maybe explain that the image has to exist before this step. 
In the end, I would like to add a section to the Wiki about containerization, so we may move things around, but for now it's fine to add this bit here in the README.

2024-03-19 10:00 UTC, greenw0lf commented on Dockerfile
> +RUN mkdir /root/.DANE /mnt/dane-fs /src /src/data
I thought that, because `/data` will be outside of the WORKDIR, it will lead to the code executed not being able to find the directory. But that's not the case, I did as you suggested and it worked. I will also change that in the README and add the information about having the image built first.

2024-03-21 07:43 UTC, Veldhoen approved these changes
Great!

2024-03-21 07:44 UTC, merged